# Generated by Django 4.0.4 on 2022-06-10 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='About Madonna Central Choir', max_length=100000, verbose_name='About Madonna Central Choir')),
                ('history', models.TextField(blank=True, max_length=100000000000, verbose_name='History of Madonna Central Choir')),
                ('logo', models.ImageField(blank=True, upload_to='logo')),
                ('Anthem', models.TextField(blank=True, max_length=10000000000)),
                ('contact', models.CharField(blank=True, max_length=10000, verbose_name='contact')),
                ('commandments', models.TextField(blank=True, max_length=10000, verbose_name='commandments')),
                ('slogan', models.CharField(blank=True, max_length=10000, verbose_name='slogan')),
                ('motto', models.CharField(blank=True, max_length=100000, verbose_name='Motto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('constitution', models.FileField(blank=True, upload_to='Constitution/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='The Date MCC was Created')),
            ],
            options={
                'verbose_name_plural': 'Abouts',
            },
        ),
    ]
