# Generated by Django 4.0.4 on 2022-06-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Anthem',
            field=models.TextField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='about',
            name='commandments',
            field=models.TextField(blank=True, max_length=100000, verbose_name='commandments'),
        ),
        migrations.AlterField(
            model_name='about',
            name='contact',
            field=models.CharField(blank=True, max_length=100000, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='about',
            name='history',
            field=models.TextField(blank=True, max_length=255, verbose_name='History of Madonna Central Choir'),
        ),
        migrations.AlterField(
            model_name='about',
            name='motto',
            field=models.CharField(blank=True, max_length=100000, verbose_name='Motto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='slogan',
            field=models.CharField(blank=True, max_length=100000, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='About Madonna Central Choir', max_length=100000, verbose_name='About Madonna Central Choir'),
        ),
    ]
