# Generated by Django 4.0.4 on 2022-06-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_video',
            name='description',
            field=models.TextField(blank=True, max_length=100000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='act_video',
            name='title',
            field=models.CharField(max_length=10000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100000, verbose_name='Title'),
        ),
    ]
