# Generated by Django 4.0.4 on 2023-01-06 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_act_video_description_alter_act_video_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_video',
            name='file',
            field=models.FileField(upload_to='Activity_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'flv', 'avi'])]),
        ),
    ]
